spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES-HOST}:${POSTGRES-PORT}/micro_weather_db_v100
    username: ${POSTGRES-USERNAME:postgres}
    password: ${POSTGRES-SECRET}
    driver-class-name: org.postgresql.Driver

micro-weather:
  wechat:
    app-id: ${WECHAT-APP-ID}
    secret: ${WECHAT-SECRET}
  data:
    service:
      public-key: ${WEATHER-SERVICE-PUBLIC-KEY}
      secret-key: ${WEATHER-SERVICE-SECRET-KEY}
  poster:
    directory: ${POSTER-CACHE-DIR:/tmp/micro-weather/data/poster/}
    key: ${POSTER-KEY}
    api: ${POSTER-API-TEMPLATE}
    proxy: ${POSTER-PROXY}

logging:
  level:
    org.fuyi.weather.infra.repository: error