server:
  port: ${SERVER_PORT:18080}

spring:
  application:
    name: micro-weather-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql