spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/micro_weather_db_v100
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_SECRET}
    driver-class-name: org.postgresql.Driver

micro-weather:
  wechat:
    app-id: ${WECHAT_APP_ID}
    secret: ${WECHAT_SECRET}
  data:
    service:
      public-key: ${WEATHER_SERVICE_PUBLIC_KEY}
      secret-key: ${WEATHER_SERVICE_SECRET_KEY}
  poster:
    directory: ${POSTER_CACHE_DIR:/tmp/micro-weather/data/poster/}
    key: ${POSTER_KEY}
    api: ${POSTER_API_TEMPLATE}
    proxy: ${POSTER_PROXY}

logging:
  level:
    org.fuyi.weather.infra.repository: error