spring:
  datasource:
    url: jdbc:postgresql://192.168.199.247:5432/micro_weather_db_v100
    username: postgres
    password: gis@4490
    driver-class-name: org.postgresql.Driver

micro-weather:
  wechat:
    app-id: ${WECHAT-APP-ID}
    secret: ${WECHAT-SECRET}
  data:
    service:
      public-key: ${WEATHER-SERVICE-PUBLIC-KEY}
      secret-key: ${WEATHER-SERVICE-SECRET-KEY}
  poster:
    directory: /tmp/micro-weather/data/poster/
    key: ${POSTER-KEY}
    api: ${POSTER-API-TEMPLATE}
    proxy: ${POSTER-PROXY}

logging:
  level:
    org.fuyi.weather.infra.repository: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"