name: Micro Weather Service Image Build And Push CI

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # setup-qemu 如果您想使用 QEMU 添加仿真支持以便能够针对更多平台进行构建，则 action 会很有用
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # setup-buildx-action 将默认使用docker-container 构建器驱动程序创建和引导构建器。非必需
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.ALIYUN_DOCKERHUB_REGISTRY}}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/fuyi-atlas/micro-weather-backend:latest
